# Generated by Django 5.0.6 on 2024-06-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_server_remove_product_digital_product_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='game',
            field=models.CharField(choices=[('Valorant', 'VALORANT'), ('League of Legends', 'LOL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.server'),
        ),
    ]
