# Generated by Django 5.0.6 on 2024-06-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_game_alter_product_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
